---

- hosts: webservers

  become: yes
  roles:
    - role: geerlingguy.pip
  collections: community.docker

  tasks:

    - name: Pull Redmine Docker image
      docker_image:
        name: redmine:latest
        source: pull
      tags: prepare

    - name: Update .env file
      template:
        src: "{{ playbook_dir }}/.env"
        dest: "{{ server_env_path }}"
      tags: deploy

    - name: Run Redmine container
      docker_container:
        name: redmine
        image: redmine
        state: started
        env_file: "{{ server_env_path }}"
        network_mode: host
      tags: deploy
