---
- hosts: localhost
  gather_facts: no
  vars_prompt:
    - name: domain_name
      prompt: What is domain name?
      default: "228.dobro-228.ru"
      private: false


  tasks:
    - name: Create terraform infrastructure (webservers)
      community.general.terraform:
        project_path: "{{ terraform_dir }}"
        variables:
          do_token: "{{ DO_TOKEN }}"
          pvt_key: "{{ DO_SSH_PVT_KEY_PATH }}"
          datadog_api_key: "{{ DATADOG_API_KEY }}"
          datadog_app_key: "{{ DATADOG_APP_KEY }}"
        force_init: yes
        state: "{{ terraform_state }}"
      tags: terraform_only
      register: infra

    - name: Create .env file
      template:
        src: "{{ playbook_dir }}/templates/.env.j2"
        dest: "{{ playbook_dir }}/.env"

    - name: Create inventory file
      template:
        src: "{{ playbook_dir }}/templates/inventory.ini.j2"
        dest: "{{ playbook_dir }}/inventory.ini"
